#!/usr/bin/env bash
# IMPORTANTE hay que tener un .my.cnf con credenciales para backup
# [client]
# user=backup
# password=
# host=localhost ; o el host remoto

# Crear un repositorio si no existe
test ! -d .git && git init

# Recorrer todas las bases de datos
echo "show databases;" | mysql | tail -n+2 | while read _database; do
# La estructura va a ser base_de_datos/tabla.mysql
  mkdir -p "${_database}"

# Recorrer todas las tablas
  printf "show tables from %s;\n" "${_database}" | \
    mysql | tail -n+2 | while read _table; do

      _backup="${_database}/${_table}.mysql"

# Cuando estamos haciendo un backup local, es mejor volcar los datos como
# valores separados por tabs
#
# TODO la documentación dice que el directorio tiene que tener permisos de
# escritura para el usuario del servidor pero me da error
#
#      mysqldump --flush-privileges \
#                --tab="${PWD}/${_database}" 2>/dev/null || \

# De lo contrario hacer un dump completo de la tabla
# No importa pisar los cambios porque los vamos a commitear
# NOTA si tenemos tablas grandes el cuello de botella va a estar acá
#
# mysqldump(1) recomienda estas flags para tablas grandes
      mysqldump --flush-privileges \
                --single-transaction \
                --events \
                --quick \
                "${_database}" "${_table}" | \
# Un registro por línea para que git no tenga que reescribir todo el archivo cada vez
                sed "s/),(/),\n(/g" >"${_backup}"

# Agregar el archivo
# TODO ver --tab
#     git add "${_database}/${_table}."*
#     git commit -a -m "etc..."
      git add "${_backup}"
# Y comitearlo con fecha y tamaño
      git commit "${_backup}" \
                 -m "${_database}.${_table} @ $(du -h "${_backup}" | cut -f1)"
  done
done

# Hacer un poco de limpieza
git gc

# Pushear si tenemos remotes
_branch="$(git rev-parse --abbrev-ref HEAD)"
git remote | while read _remote; do
  git push ${_remote} ${_branch}
done
